### ISSUE TITLE
Can't find model

### ISSUE THREAD

**Issue by tenlimba** [ShadowsAdi/CSGORemake#10]
Salut îmi da eroarea asta:
Can't find models/gox_v2_skins/knife_bayonet/v_knife_bayon model for SKINS. Line 80
L 11/01/2021 - 21:40:52: [CS:GO Remake] Can't find models/gox_v2_skins/knife_bayonet/v_knife_bayon model for SKINS. Line 80
L 11/01/2021 - 21:44:14: [CS:GO Remake] Can't find models/gox_v2_skins/knife_bayonet/v_knife_bayon model for SKINS. Line 81

Iar liniile sunt scrise în felul urmator:
"29" "Bayonet | Autotronic"      "models/gox_v2_skins/knife_bayonet/v_knife_bayonet_0.mdl"   "-"   "1"  "c"  "30" "25000"      "1"
"29" "Bayonet | Black Laminate"      "models/gox_v2_skins/knife_bayonet/v_knife_bayonet_0.mdl"   "-"   "2" "d"  "40"  "25000"      "1"

Care ar putea fi problema?
Menționez ca eu pe 1 model am mai multe texturi.

**Comment by ShadowsAdi** [comment]
Salut,
Modelul "v_knife_bayonet_0.mdl" nu poate fi gasit in locatia "models/gox_v2_skins/knife_bayonet/" verifica daca fisierul exista in acel folder. Daca exista, incearca sa reduci numele locatiei fisierului, pentru ca este limitat la 47 de caractere. O sa maresc aceste capacitati in urmatoarea actualizare.

**Comment by tenlimba** [comment]
![received_766607944734344](https://user-images.githubusercontent.com/70764621/141841391-7a75bdde-92e8-41a3-a1e1-1aa98566fbee.jpeg)
Am rezolvat mersi de ajutor dar acuma când se conectează cineva apare eroarea asta

**Comment by ShadowsAdi** [comment]
Multumesc si eu pentru feedback!
