### ISSUE TITLE
csgo spread/recoil

### ISSUE THREAD

**Issue by drag1c** [ShadowsAdi/CSGORemake#12]
Is there standard shooting or spread/recoil like in csgo? I've noticed players yelling they missing a lot. I've tested and I can agree with them.
Could there be some cvar to return old way of spraying/recoil ?

**Comment by ShadowsAdi** [comment]
Hello,
No, sorry, recoil it's from disabling client prediction ( in order to use sub-models ), so, there is no way getting it back, only with other plugin.

**Comment by drag1c** [comment]
If I understood, if we want to have, generally speaking, default recoil, we cant use sub-models?

**Comment by ShadowsAdi** [comment]
At first question: yes
Second question: no

I don't know any plugin doing this, but once disabled, client predicition can't be turned on with this mod.

**Comment by ShadowsAdi** [comment]
Inactivity, closed.

**Comment by ShadowsAdi** [comment]
Fixed in https://github.com/ShadowsAdi/CSGORemake/commit/6c2b7b3b7b5f5389ecfba0af7e799da6a9cf90f5
