### ISSUE TITLE
CSGO Remake bug la inregistrare

### ISSUE THREAD

**Issue by Gemenyx** [ShadowsAdi/CSGORemake#14]
L 01/07/2022 - 10:47:11: Column count doesn't match value count at row 1
L 01/07/2022 - 10:47:11: [MySQL] No result set in this query!
L 01/07/2022 - 10:47:11: [AMXX] Displaying debug trace (plugin "csgo_remake.amxx", version "2.14")
L 01/07/2022 - 10:47:11: [AMXX] Run time error 10: native error (native "SQL_ReadResult")
L 01/07/2022 - 10:47:11: [AMXX]    [0] csgo_remake.sma::IsTaken (line 10410)
L 01/07/2022 - 10:47:11: [AMXX]    [1] csgo_remake.sma::_SaveData (line 2718)
L 01/07/2022 - 10:47:11: [AMXX]    [2] csgo_remake.sma::_Save (line 2419)
L 01/07/2022 - 10:47:11: [AMXX]    [3] csgo_remake.sma::native_set_user_cases (line 8390)

Primesc aceste erori la inregistarea userilor prin MySQL si mai nou nu mai sunt introdusi userii noi in DB.

**Comment by ShadowsAdi** [comment]
Fixat in https://github.com/ShadowsAdi/CSGORemake/commit/30c281699a43846ba2d6b29fdd53c75565c557c6
