### ISSUE TITLE
Server Shut Down crash

### ISSUE THREAD

**Issue by ZArchiver** [ShadowsAdi/CSGORemake#15]
hi,
We getting "L 08/01/2022 - 16:53:36: (map "") Host_Error: WriteDest_Parm: not a client"   this error when pressing number in menu

**Comment by ShadowsAdi** [comment]
Hello,
In which menu do you get this error?

**Comment by ShadowsAdi** [comment]
Fixed in https://github.com/ShadowsAdi/CSGORemake/commit/1e50c9481f7cc3d6bb370581e2f4f293ca57af8f
