### ISSUE TITLE
very complex trade, players have errors when making trades...

### ISSUE THREAD

**Issue by viniciuslek159** [ShadowsAdi/CSGORemake#16]
My players and even I can't make trades, whenever we type /accept the trade is refused...
Wouldn't a trade be more convenient where the player sends the trade offer and the player receives the trade offer with the data and accepts it if he wants? It's just a suggestion... your work is amazing! Congratulations !

**Comment by ShadowsAdi** [comment]
Thank you!
I think it's more convenient this way, because, like on steam trade, both players should accept the trade, even after the second trader offers a trade offer back.
I will look into it. Can you attach a screenshot here with what you are getting in chat ( if it does return something ).

**Comment by ShadowsAdi** [comment]
Fixed in https://github.com/ShadowsAdi/CSGORemake/commit/1e50c9481f7cc3d6bb370581e2f4f293ca57af8f
