### ISSUE TITLE
Problemă gloanțe

### ISSUE THREAD

**Issue by dealerexe** [ShadowsAdi/CSGORemake#17]
Salut,
Playerii îmi reclamă faptul că gloanțele se duc aiurea rău, că e imposibil să joci.
Există vreo posibilitate să se rezolve problema asta? Pe un addons default am testat iar playerii au spus că nu sunt probleme, pe modul tău sunt.

Mersi.

**Comment by ShadowsAdi** [comment]
Salut,
Daca ai ultimul update, ar trebui sa nu mai fie aceasta problema. O sa arunc o privire cand o sa am timp liber.

**Comment by dealerexe** [comment]
Am versiunea 2.14, dar problema persistă.
