### ISSUE TITLE
Eroare

### ISSUE THREAD

**Issue by BogdanFcV** [ShadowsAdi/CSGORemake#20]
L 02/26/2022 - 21:53:18: [AMXX] Load error 17 (invalid file format or version) (plugin "csgo_remake.amxx")
L 02/26/2022 - 21:53:18: [AMXX] Load error 17 (invalid file format or version) (plugin "csgor_rankupbonus.amxx")
L 02/26/2022 - 21:53:18: [AMXX] Load error 17 (invalid file format or version) (plugin "csgor_regbonus.amxx")
L 02/26/2022 - 21:53:18: [AMXX] Load error 17 (invalid file format or version) (plugin "csgor_warmweapons.amxx")
L 02/26/2022 - 21:53:18: [AMXX] Load error 17 (invalid file format or version) (plugin "csgor_giveaway.amxx")

**Comment by ShadowsAdi** [comment]
Inchis datorita inactivitatii.
