### ISSUE TITLE
Active Skin bug

### ISSUE THREAD

**Issue by StanchuZ** [ShadowsAdi/CSGORemake#21]
So I noticed a problem with the hud when you get other player's wepon it will show your active skin and you can gain "Confirmed Kills" with it even tho that's not your skin and if it's not stattrack it will just show no active skin even tho it's not a big of a deal I can switch the hud cvar to 1 and not display the skin name and confirmed kills it would be good if you re-work the hud or fix the issue.
![20220314205109_1](https://user-images.githubusercontent.com/101092501/158242912-b4013efd-59b3-4429-a529-cacb7c4b2d04.jpg)
![20220314205640_1](https://user-images.githubusercontent.com/101092501/158242926-8f2b275b-e128-4d84-a1c8-1ef6b5ecea50.jpg)

**Comment by ShadowsAdi** [comment]
Hello,
What is "/skin" command showing? Is it showing the correct skin name?

**Comment by StanchuZ** [comment]
It's showing the skin that you are holding when I type it but on the hud is the skin that I have selected
![Uploading 20220315150344_1.jpg…]()

**Comment by ShadowsAdi** [comment]
Should be fixed now, thank you for your contribution. I will leave this topic open until your answear.

**Comment by StanchuZ** [comment]
thank you!
I will keep you updated if I find any more bugs

**Comment by ShadowsAdi** [comment]
Fixed in https://github.com/ShadowsAdi/CSGORemake/commit/d1b2f4c68986363ecf76d448dc1b30dd2b0c3b71

**Comment by StanchuZ** [comment]
new problem now I can't open cases, the menu is just closing itself

**Comment by ShadowsAdi** [comment]
Yes, that's it from cooldown, your chance at that moment is less that the cvar's chance, that's why, maybe I will make another way to do it. Until then it stays right it is now.
