### ISSUE TITLE
Case/Dust Opening

### ISSUE THREAD

**Issue by Annoucement** [ShadowsAdi/CSGORemake#22]
Hello, whenever you open cases and dusts, you need to wait 5 seconds, is it possible to remove this cooldown or change it?

**Comment by ShadowsAdi** [comment]
Fixed in https://github.com/ShadowsAdi/CSGORemake/commit/33fcea6a8fe00b8ce041e18e37c15066061b52ff

**Comment by ShadowsAdi** [comment]
Solved in #23
