### ISSUE TITLE
bonus bug or cheat

### ISSUE THREAD

**Issue by viniciuslek159** [ShadowsAdi/CSGORemake#24]
Could you make a system that solves the following situation:

With the bonus enabled, players are creating fake account and getting bonus and sending it to the original account.

  in less than seconds they can create several accounts with different nicks... in this case 1 player creates accounts with nicks abc bcd 123 321 1234 Etc they get both skins keys and boxes and send them to their original account...
at the moment I disable the bonus and activate it again once a week because this type of cheating always happens

**Comment by ShadowsAdi** [comment]
Hello,
Do you mean this plugin? https://github.com/ShadowsAdi/CSGORemake/blob/master/addons/amxmodx/scripting/csgor_giveaway.sma ?
If so, yes, I could make a check for player's steam ID or IP.

**Comment by viniciuslek159** [comment]
the bonus of say /bonus... where you get Skin, Cases, Dust to choose from, I believe it's in csgo remake.sma

**Comment by viniciuslek159** [comment]
As the server for most is on steam, I think by IP it would be more convenient, because by id few have steam. or put a Cvar to be able to check both for steam or IP

**Comment by ShadowsAdi** [comment]
Solved in #26
