### ISSUE TITLE
Stattrack

### ISSUE THREAD

**Issue by kvki15narkusr** [ShadowsAdi/CSGORemake#27]
Hello, idk is this an issue or not, but stattrack skin cannot be traded, destroyed or selled in market. Btw contract would be awesome for example you stack like 5 m4a1 | Decimator skins and with contract you can switch it to 1 StatTrack M4A1 | Decimator.

**Comment by ShadowsAdi** [comment]
Hello,
Stattrack system is not fully implemented, will be coming soon. It is tracked here: https://github.com/ShadowsAdi/CSGORemake/projects/1

**Comment by kvki15narkusr** [comment]
Awesome!
