### ISSUE TITLE
permission 777 plugins ftp 

### ISSUE THREAD

**Issue by boriscois** [ShadowsAdi/csgoremake#3]
Failed to auto generate config for csgo_remake.amxx, make sure the directory has write permission.

**Comment by ShadowsAdi** [comment]
Your addons/amxmodx/configs directory doesn't have write permission to create a new folder there. You can create by your own a folder inside configs called plugins and then the plugin will create the configuration file.

**Comment by boriscois** [comment]
Its working thx
