### ISSUE TITLE
6 digit money bug

### ISSUE THREAD

**Issue by viniciuslek159** [ShadowsAdi/CSGORemake#33]
when the player reaches the mark of 6 digits of money on the server automatically the server takes the last digit in the case if the player has 100001, when he relogs he has only 10000...
It's hard to get to the value, but it happened because they bet 50000 on roulette and won!

**Comment by ShadowsAdi** [comment]
Hello,
Is this happens while nvault saving is active or mysql one?

**Comment by ShadowsAdi** [comment]
Fixed in #34

**Comment by viniciuslek159** [comment]
thanks my friend
