### ISSUE TITLE
native error

### ISSUE THREAD

**Issue by boriscois** [ShadowsAdi/csgoremake#4]
Function "native_csgor_is_last_round" was not found
 [AMXX] Run time error 19 (plugin "csgo_remake.amxx") - debug not enabled!
 [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
[AMXX] Run time error -1 (plugin "csgo_remake.amxx") - debug not enabled!
An error occurred in plugin_natives. This is dangerous!

[AMXX] Plugin not compiled with debug option (plugin "csgo_remake.amxx")

**Comment by ShadowsAdi** [comment]
Solved, thanks.
