### ISSUE TITLE
Competitive

### ISSUE THREAD

**Issue by Eugen3000** [ShadowsAdi/CSGORemake#40]
Salut , cum pot scoate modul competitive ?

**Comment by ShadowsAdi** [comment]
Salut, 
Toate setarile se gasesc in [csgo_remake.cfg](https://github.com/ShadowsAdi/CSGORemake/blob/master/addons/amxmodx/configs/plugins/csgor/csgo_remake.cfg), precum scrie si in [ReadMe](https://github.com/ShadowsAdi/CSGORemake#config) .


https://github.com/ShadowsAdi/CSGORemake/blob/master/addons/amxmodx/configs/plugins/csgor/csgo_remake.cfg#L226-L234
