### ISSUE TITLE
m4/sg550 buy crash

### ISSUE THREAD

**Issue by boriscois** [ShadowsAdi/csgoremake#5]
FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/csgor/v_m4a4_0.mdl not precached
Segmentation fault (core dumped)
email debug.log to linux@valvesoftware.com

FATAL ERROR (shutting down): SV_ModelIndex: SV_ModelIndex: model models/sg550/v_sg550.mdl not precached

**Comment by ShadowsAdi** [comment]
Solved v_sg550.mdl issue. For v_m4a4_0.mdl, I added new skins for M4A4 and P90, you need to update your csgor_configs.ini too.
Download latest release from [here](https://github.com/ShadowsAdi/csgoremake/releases/latest)
