### ISSUE TITLE
Remembering login

### ISSUE THREAD

**Issue by karsky91** [ShadowsAdi/CSGORemake#56]
Hello, 

is it possible to create a remembered login?

**Comment by ShadowsAdi** [comment]
Hello,
Mod has this feature already: typing "/savepass" in chat will save your password in userinfo and insert it automatically for next server connect. Or you have another idea in mind?

**Comment by karsky91** [comment]
ok, could this be done automatically? For example, as confirmation of registration? :)

**Comment by karsky91** [comment]
and when I write setinfo _pass "" in the console and connect again, I have to login

**Comment by ShadowsAdi** [comment]
I understood the feature now. Working on an update right now.

**Comment by ShadowsAdi** [comment]
Fixed in #57
