### ISSUE TITLE
Problema viewmodel

### ISSUE THREAD

**Issue by NomaDD26** [ShadowsAdi/CSGORemake#7]
Bugul consta atunci cand dai switch intre jucatori , o sa vezi skinuri random pe arme ptr cateve milisecunde ! Link de la video 👍 

PS1 : daca poti adauga : 
- daca jucatorul x are AWP DRAGON LORE si arunca awp-ul pe jos iar playerul y care are setat pe awp - skinul ASIIMOV - ia acel awp de pe jos, sa aiba tot skinul DRAGON LORE, nu cel default sau cel pe care il are setat 

https://www.youtube.com/watch?v=PB-A6jgU0fw

Sper ca te-am ajutat ! Oricum vad potential in acest mod ! Succes :)

Edit 1 : Am mai gasit un mic bug la coinflip ,cateodata merge sa dai coinflip cu cineva, cateodata zice ca nu am un request de coinflip

**Comment by ShadowsAdi** [comment]
O sa revizui animatia pentru spectatori.
Da, o sa lucrez si la retinerea skin-ului aruncat de catre alt jucator pe jos.

O sa ma uit peste coinflip.
Multumesc pentru suport. Apreciez.

**Comment by NomaDD26** [comment]
O mica idee , dar nu stiu daca se poate implementa : 
Sa se poata modifica meniul dintr-un fisier .ini extern din ftp 
Gen sa fie ceva de genu  :) 👍 :

"Nume linie meniu" "public apelat"
"Nume linie 2" "alt public apelat"

pentru ca lumea sa mai poata / scoate linii din meniu in caz ca vor
